/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppProgressRouteImport } from './routes/app.progress'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppMealsRouteImport } from './routes/app.meals'
import { Route as AppInbodyRouteImport } from './routes/app.inbody'
import { Route as AppFormRouteImport } from './routes/app.form'
import { Route as AppCoachRouteImport } from './routes/app.coach'
import { Route as AppWorkoutsIndexRouteImport } from './routes/app.workouts.index'
import { Route as AppWorkoutsIdRouteImport } from './routes/app.workouts.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppProgressRoute = AppProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMealsRoute = AppMealsRouteImport.update({
  id: '/meals',
  path: '/meals',
  getParentRoute: () => AppRoute,
} as any)
const AppInbodyRoute = AppInbodyRouteImport.update({
  id: '/inbody',
  path: '/inbody',
  getParentRoute: () => AppRoute,
} as any)
const AppFormRoute = AppFormRouteImport.update({
  id: '/form',
  path: '/form',
  getParentRoute: () => AppRoute,
} as any)
const AppCoachRoute = AppCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkoutsIndexRoute = AppWorkoutsIndexRouteImport.update({
  id: '/workouts/',
  path: '/workouts/',
  getParentRoute: () => AppRoute,
} as any)
const AppWorkoutsIdRoute = AppWorkoutsIdRouteImport.update({
  id: '/workouts/$id',
  path: '/workouts/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/coach': typeof AppCoachRoute
  '/app/form': typeof AppFormRoute
  '/app/inbody': typeof AppInbodyRoute
  '/app/meals': typeof AppMealsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/progress': typeof AppProgressRoute
  '/app/': typeof AppIndexRoute
  '/app/workouts/$id': typeof AppWorkoutsIdRoute
  '/app/workouts/': typeof AppWorkoutsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/app/coach': typeof AppCoachRoute
  '/app/form': typeof AppFormRoute
  '/app/inbody': typeof AppInbodyRoute
  '/app/meals': typeof AppMealsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/progress': typeof AppProgressRoute
  '/app': typeof AppIndexRoute
  '/app/workouts/$id': typeof AppWorkoutsIdRoute
  '/app/workouts': typeof AppWorkoutsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/app/coach': typeof AppCoachRoute
  '/app/form': typeof AppFormRoute
  '/app/inbody': typeof AppInbodyRoute
  '/app/meals': typeof AppMealsRoute
  '/app/profile': typeof AppProfileRoute
  '/app/progress': typeof AppProgressRoute
  '/app/': typeof AppIndexRoute
  '/app/workouts/$id': typeof AppWorkoutsIdRoute
  '/app/workouts/': typeof AppWorkoutsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/auth'
    | '/app/coach'
    | '/app/form'
    | '/app/inbody'
    | '/app/meals'
    | '/app/profile'
    | '/app/progress'
    | '/app/'
    | '/app/workouts/$id'
    | '/app/workouts/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/app/coach'
    | '/app/form'
    | '/app/inbody'
    | '/app/meals'
    | '/app/profile'
    | '/app/progress'
    | '/app'
    | '/app/workouts/$id'
    | '/app/workouts'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/auth'
    | '/app/coach'
    | '/app/form'
    | '/app/inbody'
    | '/app/meals'
    | '/app/profile'
    | '/app/progress'
    | '/app/'
    | '/app/workouts/$id'
    | '/app/workouts/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/progress': {
      id: '/app/progress'
      path: '/progress'
      fullPath: '/app/progress'
      preLoaderRoute: typeof AppProgressRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/meals': {
      id: '/app/meals'
      path: '/meals'
      fullPath: '/app/meals'
      preLoaderRoute: typeof AppMealsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/inbody': {
      id: '/app/inbody'
      path: '/inbody'
      fullPath: '/app/inbody'
      preLoaderRoute: typeof AppInbodyRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/form': {
      id: '/app/form'
      path: '/form'
      fullPath: '/app/form'
      preLoaderRoute: typeof AppFormRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/coach': {
      id: '/app/coach'
      path: '/coach'
      fullPath: '/app/coach'
      preLoaderRoute: typeof AppCoachRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/workouts/': {
      id: '/app/workouts/'
      path: '/workouts'
      fullPath: '/app/workouts/'
      preLoaderRoute: typeof AppWorkoutsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/workouts/$id': {
      id: '/app/workouts/$id'
      path: '/workouts/$id'
      fullPath: '/app/workouts/$id'
      preLoaderRoute: typeof AppWorkoutsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppCoachRoute: typeof AppCoachRoute
  AppFormRoute: typeof AppFormRoute
  AppInbodyRoute: typeof AppInbodyRoute
  AppMealsRoute: typeof AppMealsRoute
  AppProfileRoute: typeof AppProfileRoute
  AppProgressRoute: typeof AppProgressRoute
  AppIndexRoute: typeof AppIndexRoute
  AppWorkoutsIdRoute: typeof AppWorkoutsIdRoute
  AppWorkoutsIndexRoute: typeof AppWorkoutsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppCoachRoute: AppCoachRoute,
  AppFormRoute: AppFormRoute,
  AppInbodyRoute: AppInbodyRoute,
  AppMealsRoute: AppMealsRoute,
  AppProfileRoute: AppProfileRoute,
  AppProgressRoute: AppProgressRoute,
  AppIndexRoute: AppIndexRoute,
  AppWorkoutsIdRoute: AppWorkoutsIdRoute,
  AppWorkoutsIndexRoute: AppWorkoutsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
